eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
server:
  port: 8761
spring:
  application:
    name: eureka-server
  http:
    encoding:
      charset: utf-8
      force: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  security:
    user:
      name: test
      password: test